### ISSUE TITLE
Running proofreader shows Exception classes with inconsistent naming

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/api-sdk-php#14]
```
$ ../proofreader-php/bin/proofreader src/                                                                                    
PHP-CS-Fixer consistency check with local project
PHP-CS-Fixer
Loaded config from "/home/giorgio/code/proofreader-php/.php_cs.dist"
...................
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Checked all files in 1.365 seconds, 6.000 MB memory used
PHPMD

/home/giorgio/code/api-sdk-php/src/Exception/ApiException.php:8 Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/ApiProblemException.php:10 Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/HttpException.php:8        Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/NetworkException.php:5     Do not suffix exception names with Exception
/home/giorgio/code/api-sdk-php/src/Exception/ResponseException.php:9    Do not suffix exception names with Exception
PHPCPD
phpcpd 2.0.4 by Sebastian Bergmann.

0.00% duplicated lines out of 649 total lines of code.

Time: 38 ms, Memory: 2.00MB
```

Who's right, this code or the coding standard telling us not to use the `*Exception` suffix?

**Comment by thewilkybarkid** [comment]
If they're technical rather than domain failures, the rule does feel a little less important. That said, it might be possible to give them better names...

`ApiException` ➞ ?
`ApiProblemException` ➞ `ApiProblem` (this does mean it has the same name as the wrapped object, maybe `ApiProblemResponse`?)
`HttpException` ➞ `HttpProblem`
`NetworkException` ➞ `NetworkProblem`
`ResponseException` ➞ `BadResponse`

**Comment by giorgiosironi** [comment]
If the changes are self-contained to this project I can make them and open a PR that has the `proofreader` command being executed and passing.
If we don't want to do it, we can add a `@SuppressWarnings` annotation to these classes to allow them to be named like this.
